from __future__ import annotations

from pathlib import Path


MARKERS_BY_TEST_FILE = {
    "test_channel_topology_graph_adapter.py": ("adapter_contract",),
    "test_coverage_planner.py": ("formal_contract",),
    "test_coverage_planning_diagnostics_contract.py": ("formal_contract",),
    "test_coverage_planner_modes.py": ("formal_contract",),
    "test_coverage_preprocessing.py": ("formal_contract",),
    "test_coverage_quality_guard.py": ("formal_contract",),
    "test_coverage_repo_export_diagnostics.py": ("export_contract",),
    "test_coverage_repo_export_planner_modes.py": ("export_contract",),
    "test_coverage_repo_import.py": ("export_contract",),
    "test_coverage_request_contract.py": ("formal_contract",),
    "test_coverage_router.py": ("formal_contract", "adapter_contract"),
    "test_main_window_flow.py": ("ui_contract",),
    "test_maptools_coverage_planning_adapter.py": ("formal_contract", "adapter_contract"),
    "test_planner_factory_modes.py": ("formal_contract",),
    "test_shelf_aware_artifact_write_stage.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_artifact_outputs.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_final_path_realization.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_final_path_transform_record.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_final_provenance.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_coverage_graph_stage.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_direction_field_stage.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_energy_planner_wiring.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_grid_builder.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_grid_topology.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_graph_traversal_stage.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_input_validation_stage.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_node_filtering.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_node_generation_profiles.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_node_truth_boundaries.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_output_assembly.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_path_jump_cleanup.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_room_rotation_stage.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_start_cell_stage.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_traversal_candidate_summary.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_traversal_decision_debug.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_traversal_candidate_enumeration.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_traversal_history_clearance.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_traversal_move_commit.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_traversal_phase_selectors.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_traversal_reachability.py": ("shelf_grid", "formal_contract"),
    "test_shelf_aware_traversal_roles.py": ("shelf_grid", "formal_contract"),
    "test_turn_cost_annotated_window_alignment.py": ("readonly_diagnostic",),
    "test_turn_cost_annotated_window_attribution.py": ("readonly_diagnostic",),
    "test_turn_cost_batch_reconnect_provenance.py": ("research_experiment",),
    "test_turn_cost_candidate_baseline_gate.py": ("formal_contract",),
    "test_turn_cost_delivery_gate.py": ("formal_contract",),
    "test_turn_cost_guidance_ab_case.py": ("reference_reproduction", "optional_env"),
    "test_turn_cost_guidance_cli_contract.py": ("reference_reproduction",),
    "test_turn_cost_guidance_vertex_query.py": ("reference_reproduction",),
    "test_turn_cost_guided_atomic_strips.py": ("reference_reproduction",),
    "test_turn_cost_highs_fractional_solver.py": ("reference_reproduction", "optional_env"),
    "test_turn_cost_lane_family_blocker_attribution.py": ("research_experiment",),
    "test_turn_cost_lane_family_reconstruction.py": ("research_experiment",),
    "test_turn_cost_maptools_official_adapter.py": ("reference_reproduction", "optional_env"),
    "test_turn_cost_official_summary_contract.py": ("reference_reproduction",),
    "test_turn_cost_output_asset_manifest.py": ("readonly_diagnostic",),
    "test_turn_cost_path_diagnostics.py": ("readonly_diagnostic",),
    "test_turn_cost_path_lane_spacing_balancer.py": ("research_experiment",),
    "test_turn_cost_path_lane_window_inspector.py": ("readonly_diagnostic",),
    "test_turn_cost_path_local_reconnector.py": ("research_experiment",),
    "test_turn_cost_path_post_optimizer.py": ("research_experiment",),
    "test_turn_cost_path_quality_guarded_optimizer.py": ("research_experiment",),
    "test_turn_cost_shelf_direction_adapter.py": ("reference_reproduction",),
    "test_turn_cost_script_layout.py": ("formal_contract",),
    "test_turn_cost_square8_axis_graph.py": ("reference_reproduction",),
}


def pytest_collection_modifyitems(config, items):
    for item in items:
        filename = Path(str(item.fspath)).name
        for marker in MARKERS_BY_TEST_FILE.get(filename, ()):
            item.add_marker(marker)
