"""Junction rebuild 渲染配色常量。"""

_SKELETON_COLOR = (150, 150, 150)
_POLYGON_COLOR = (0, 255, 0)
_FULL_PATH_COLOR = (255, 0, 255)
_INNER_PATH_COLOR = (0, 128, 255)
_OUTER_PATH_COLOR = (255, 96, 0)
_NODE_COLOR = (0, 0, 255)
_AUX_GEOMETRY_COLOR = (255, 128, 0)
_AUX_SCAN_COLOR = (255, 192, 96)
_NODE_TEXT_FILL = (0, 0, 255)
_EDGE_TEXT_FILL = (255, 0, 255)

SKELETON_COLOR = _SKELETON_COLOR
POLYGON_COLOR = _POLYGON_COLOR
FULL_PATH_COLOR = _FULL_PATH_COLOR
INNER_PATH_COLOR = _INNER_PATH_COLOR
OUTER_PATH_COLOR = _OUTER_PATH_COLOR
NODE_COLOR = _NODE_COLOR
AUX_GEOMETRY_COLOR = _AUX_GEOMETRY_COLOR
AUX_SCAN_COLOR = _AUX_SCAN_COLOR
NODE_TEXT_FILL = _NODE_TEXT_FILL
EDGE_TEXT_FILL = _EDGE_TEXT_FILL

__all__ = [
    "SKELETON_COLOR",
    "POLYGON_COLOR",
    "FULL_PATH_COLOR",
    "INNER_PATH_COLOR",
    "OUTER_PATH_COLOR",
    "NODE_COLOR",
    "AUX_GEOMETRY_COLOR",
    "AUX_SCAN_COLOR",
    "NODE_TEXT_FILL",
    "EDGE_TEXT_FILL",
]
