"""Coverage-planning algorithm domain."""

from .contracts import (
    ApplicabilityMetrics,
    ApplicabilityResult,
    apply_planner_mode_defaults,
    build_coverage_planning_request_configs,
    coverage_planner_config_diff,
    coverage_planner_mode_default_overrides,
    coverage_planner_profile_metadata,
    CoveragePlannerConfig,
    CoveragePlannerPrivateConfig,
    CoverageResult,
    CoveragePlanningDiagnostics,
    CoveragePlanningFinalPathSummary,
    CoveragePlanningFinalPathValidation,
    CoveragePlanningPipelineMeta,
    CoveragePlanningRuntimeDetails,
    CoveragePlanningRequest,
    CoveragePlanningResult,
    CoveragePlanningStatus,
    CoveragePose2D,
    Pose2D,
    SHELF_AWARE_MODE,
    SHELF_AWARE_TURN_COST_MODE,
    SHELF_AWARE_TURN_COST_NODE_GENERATION_MODE,
    SHELF_AWARE_TURN_COST_REPAIRED_GRID_MAX_OFFSET_FACTOR,
    build_private_coverage_planner_config,
    coverage_planner_config_to_dict,
    normalize_coverage_planner_config_dict,
)
from .planner_factory import check_optional_planner_dependencies, create_coverage_planner, run_formal_planner_request
from .routing import route_coverage_plan

__all__ = [
    "ApplicabilityMetrics",
    "ApplicabilityResult",
    "apply_planner_mode_defaults",
    "build_coverage_planning_request_configs",
    "coverage_planner_config_diff",
    "coverage_planner_mode_default_overrides",
    "coverage_planner_profile_metadata",
    "CoveragePlannerConfig",
    "CoveragePlannerPrivateConfig",
    "CoverageResult",
    "CoveragePlanningDiagnostics",
    "CoveragePlanningFinalPathSummary",
    "CoveragePlanningFinalPathValidation",
    "CoveragePlanningPipelineMeta",
    "CoveragePlanningRuntimeDetails",
    "CoveragePlanningRequest",
    "CoveragePlanningResult",
    "CoveragePlanningStatus",
    "CoveragePose2D",
    "Pose2D",
    "SHELF_AWARE_MODE",
    "SHELF_AWARE_TURN_COST_MODE",
    "SHELF_AWARE_TURN_COST_NODE_GENERATION_MODE",
    "SHELF_AWARE_TURN_COST_REPAIRED_GRID_MAX_OFFSET_FACTOR",
    "build_private_coverage_planner_config",
    "coverage_planner_config_to_dict",
    "normalize_coverage_planner_config_dict",
    "check_optional_planner_dependencies",
    "create_coverage_planner",
    "run_formal_planner_request",
    "route_coverage_plan",
]
